name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        go-versions: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-
    - uses: actions/cache@v1
      with:
        path: ~/.build/go-cache
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-
    - name: go env
      run: go env
    - name: Fetch dependencies
      run: go get
    - name: Run tests
      run: go test ./...
    - name: Build
      run: go build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-
      - uses: actions/cache@v1
        with:
          path: ~/.build/go-cache
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-
      - name: Lint
        run: |
          docker run -e GOCACHE=/go/.cache -v ~/.cache/go-build:/go/.cache -v ~/go/pkg/mod:/go/pkg/mod -e GO111MODULE --rm -v `pwd`:/go/src/github.com/virtual-kubelet/node-cli -w /go/src/github.com/virtual-kubelet/node-cli \
            golangci/golangci-lint:v1.23.8 golangci-lint run --disable-all -v \
            -E govet -E misspell -E gofmt -E ineffassign -E golint
